---
title: "advent of code - 2025"
format: html
---

```{r}
library(here)
library(tidyverse)
```

# DAY 1

## PUZZLE 1

### TEST

```{r}
df <- read_lines(here("day1_df.txt")) |> 
        as_tibble() |> 
        separate_wider_position(value, c(direction = 1, unit = 2), too_few = "align_start") |>
        mutate(unit = as.numeric(unit)) |>
        mutate(move = case_when(direction == "L" ~ -unit,
                                    TRUE ~ unit)) |>
        mutate(moved_to = 50 + cumsum(move)) |>
        mutate(moved_to2 = case_when(moved_to < 0 ~ as.numeric(str_sub(moved_to + 100, -2)), 
                                        moved_to > 100 ~ as.numeric(str_sub(moved_to, -2)), TRUE ~ moved_to))

password <- df |> filter(moved_to2 == 0) |> nrow()
```

### PUZZLE

```{r}
puzzle1 <- read_lines(here("day1_puzzle1.txt")) |> 
        as_tibble() |> 
        separate_wider_position(value, c(direction = 1, unit = 5), too_few = "align_start") |>
        mutate(unit = as.numeric(unit)) |>
        mutate(move = case_when(direction == "L" ~ -unit,
                                    TRUE ~ unit)) |>
        mutate(moved_to = 50 + cumsum(move)) |>
        mutate(moved_to2 = case_when(moved_to < 0 ~ as.numeric(str_sub(moved_to + 100, -2)), 
                                        moved_to >= 100 ~ as.numeric(str_sub(moved_to, -2)), TRUE ~ moved_to))

puzzle1 |> summarise(min(moved_to2), max(moved_to2))

password <- puzzle1 |> filter(moved_to2 == 0) |> nrow()
```

## PUZZLE 2

### TEST

```{r}
test1 <- read_lines(here("day1_test1.txt")) |> 
        as_tibble() |> 
        separate_wider_position(value, c(direction = 1, unit = 3), too_few = "align_start") |>
        mutate(unit = as.numeric(unit)) |>
        mutate(start = if_else(row_number() == 1, 50, NA), check = 0, end=NA, factor = 1)

df <- test1

for (i in 1:nrow(df)){

        if (df$unit[i] >= 100){
                df$factor[i] <- floor(df$unit[i]/100)
                df$unit[i] <- df$unit[i] - 100 * df$factor[i]
                df$check[i] <- df$factor[i]
        }
        if(df$direction[i] == "R" & df$start[i]  + df$unit[i]  < 100){
                df$end[i] <- df$start[i]  + df$unit[i] 
        } else if (df$direction[i] == "R" & df$start[i]  + df$unit[i]  >= 100){
                df$end[i] <- df$start[i]  + df$unit[i] -  100
                df$check[i] <- df$check[i] + 1 
        } else if (df$direction[i] == "L" & df$start[i] - df$unit[i]  < 0 ){
                df$end[i] <- 100 + (df$start[i] - df$unit[i])
                if (df$start[i] != 0){
                 df$check[i] <- df$check[i] + 1
                }
        } else if (df$direction[i] == "L" &  df$start[i] - df$unit[i]  > 0){
                df$end[i] <- df$start[i] - df$unit[i]
        } else if (df$direction[i] == "L" &  df$start[i] - df$unit[i]  == 0){
                df$end[i] <- df$start[i] - df$unit[i]
                if (df$start[i] != 0){
                 df$check[i] <- df$check[i] + 1
                }
        }
        df$start[i+1] <- df$end[i]
}


df

password <- df |> filter(check == 1) |> nrow()
password
```

### PUZZLE

```{r}
puzzle2 <- read_lines(here("day1_puzzle1.txt")) |> 
        as_tibble() |> 
        separate_wider_position(value, c(direction = 1, unit = 3), too_few = "align_start") |>
        mutate(unit = as.numeric(unit)) |>
        mutate(start = if_else(row_number() == 1, 50, NA), check = 0, end=NA, factor = 1)

puzzle2 |> View()

df <- puzzle2
        
for (i in 1:nrow(df)){

        if (df$unit[i] >= 100){
                df$factor[i] <- floor(df$unit[i]/100)
                df$unit[i] <- df$unit[i] - 100 * df$factor[i]
                df$check[i] <- df$factor[i]
        }
        if(df$direction[i] == "R" & df$start[i]  + df$unit[i]  < 100){
                df$end[i] <- df$start[i]  + df$unit[i] 
        } else if (df$direction[i] == "R" & df$start[i]  + df$unit[i]  >= 100){
                df$end[i] <- df$start[i]  + df$unit[i] -  100
                df$check[i] <- df$check[i] + 1 
        } else if (df$direction[i] == "L" & df$start[i] - df$unit[i]  < 0 ){
                df$end[i] <- 100 + (df$start[i] - df$unit[i])
                if (df$start[i] != 0){
                 df$check[i] <- df$check[i] + 1
                }
        } else if (df$direction[i] == "L" &  df$start[i] - df$unit[i]  > 0){
                df$end[i] <- df$start[i] - df$unit[i]
        } else if (df$direction[i] == "L" &  df$start[i] - df$unit[i]  == 0){
                df$end[i] <- df$start[i] - df$unit[i]
                if (df$start[i] != 0){
                 df$check[i] <- df$check[i] + 1
                }
        }
        df$start[i+1] <- df$end[i]
}

df |>  View()

password <- df |> summarise(sum(check, na.rm=T))
password
```

# DAY 2

## PUZZLE 1

### TEST

```{r}
test1 <- read_lines(here("day2_test1.txt")) |>
        as_tibble() |>
        separate_longer_delim(value, ",") |>
        separate_wider_delim(value, delim = "-", names = c("start", "end"))

df <- test1

invalid_sum <- 0
for (i in 1:nrow(df)){
        numbers <- as.numeric(df$start[i]):as.numeric(df$end[i])
        for (j in 1:length(numbers)){
        if (floor(str_length(numbers[j])/2) == str_length(numbers[j])/2){
                if(str_sub(numbers[j],1,str_length(numbers[j])/2) == str_sub(numbers[j], str_length(numbers[j])/2 + 1, str_length(numbers[j]))){
                        invalid_sum <- invalid_sum + numbers[j]
                }
        }  
}

}
invalid_sum
```

### PUZZLE

```{r}
puzzle1 <- read_lines(here("day2_puzzle1.txt")) |>
        as_tibble() |>
        separate_longer_delim(value, ",") |>
        separate_wider_delim(value, delim = "-", names = c("start", "end"))

df <- puzzle1

invalid_sum <- 0
for (i in 1:nrow(df)){
        numbers <- as.numeric(df$start[i]):as.numeric(df$end[i])
        for (j in 1:length(numbers)){
        if (floor(str_length(numbers[j])/2) == str_length(numbers[j])/2){
                if(str_sub(numbers[j],1,str_length(numbers[j])/2) == str_sub(numbers[j], str_length(numbers[j])/2 + 1, str_length(numbers[j]))){
                        invalid_sum <- invalid_sum + numbers[j]
                }
        }  
}

}
invalid_sum
```

## PUZZLE 2

### TEST

```{r}
test1 <- read_lines(here("day2_test1.txt")) |>
        as_tibble() |>
        separate_longer_delim(value, ",") |>
        separate_wider_delim(value, delim = "-", names = c("start", "end"))

df <- test1

max_length <- max(str_length(test1$end))

invalid_sum <- 0
for (i in 1:nrow(df)){
        numbers <- as.numeric(df$start[i]):as.numeric(df$end[i])
        for (j in 1:length(numbers)){
                len_num <- str_length(numbers[j])
                if (len_num == 10){
                        if(str_sub(numbers[j], 1, 5) == str_sub(numbers[j], 6, 10)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        } else if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 5, 6) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 7, 8) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 9, 10)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        } 
                }
                if (len_num == 9){
                        if(str_sub(numbers[j], 1, 3) == str_sub(numbers[j], 4, 6) & str_sub(numbers[j], 1, 3) == str_sub(numbers[j], 7, 9)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        } 
                }
                if (len_num == 8){
                        if(str_sub(numbers[j], 1, 4) == str_sub(numbers[j], 5, 8)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        } else if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 5, 6) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 7, 8)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        } 
                }
                if (len_num == 6){
                        if(str_sub(numbers[j], 1, 3) == str_sub(numbers[j], 4, 6)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        } else if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 5, 6)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        } 
                }
                if (len_num == 4){
                        if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4)){
                                invalid_sum <- invalid_sum + numbers[j]
                                print(numbers[j])
                        }
                }
                if (len_num %in% c(2, 3, 5, 7) & all(str_split(numbers[j], "") |> unlist() == str_sub(numbers[j], 1, 1))){
                        invalid_sum <- invalid_sum + numbers[j]
                        print(numbers[j])
                }
        }
}
invalid_sum
```

### PUZZLE

```{r}
puzzle2 <- read_lines(here("day2_puzzle1.txt")) |>
        as_tibble() |>
        separate_longer_delim(value, ",") |>
        separate_wider_delim(value, delim = "-", names = c("start", "end"))

df <- puzzle2


max_length <- max(str_length(df$end))

invalid_sum <- 0
for (i in 1:nrow(df)){
        numbers <- as.numeric(df$start[i]):as.numeric(df$end[i])
        for (j in 1:length(numbers)){
                len_num <- str_length(numbers[j])
                if (len_num == 10){
                        if(str_sub(numbers[j], 1, 5) == str_sub(numbers[j], 6, 10)){
                                invalid_sum <- invalid_sum + numbers[j]
                        } else if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 5, 6) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 7, 8) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 9, 10)){
                                invalid_sum <- invalid_sum + numbers[j]
                        } 
                }
                if (len_num == 9){
                        if(str_sub(numbers[j], 1, 3) == str_sub(numbers[j], 4, 6) & str_sub(numbers[j], 1, 3) == str_sub(numbers[j], 7, 9)){
                                invalid_sum <- invalid_sum + numbers[j]
                        } 
                }
                if (len_num == 8){
                        if(str_sub(numbers[j], 1, 4) == str_sub(numbers[j], 5, 8)){
                                invalid_sum <- invalid_sum + numbers[j]
                        } else if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 5, 6) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 7, 8)){
                                invalid_sum <- invalid_sum + numbers[j]
                        } 
                }
                if (len_num == 6){
                        if(str_sub(numbers[j], 1, 3) == str_sub(numbers[j], 4, 6)){
                                invalid_sum <- invalid_sum + numbers[j]
                        } else if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4) & str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 5, 6)){
                                invalid_sum <- invalid_sum + numbers[j]
                        } 
                }
                if (len_num == 4){
                        if(str_sub(numbers[j], 1, 2) == str_sub(numbers[j], 3, 4)){
                                invalid_sum <- invalid_sum + numbers[j]
                        }
                }
                if (len_num %in% c(2, 3, 5, 7) & all(str_split(numbers[j], "") |> unlist() == str_sub(numbers[j], 1, 1))){
                        invalid_sum <- invalid_sum + numbers[j]
                }
        }
}
invalid_sum

```

# DAY 3

## PUZZLE 1

### TEST


```{r}
test1 <- read_lines(here("day3_test1.txt")) |>
        as_tibble() 

df <- test1
sum_num <- 0

for (i in 1:nrow(df)){
        len_num <- str_length(as.character(df$value[i]))
        max1 <- max(as.numeric(str_extract_all(df$value[i], "") |> unlist()))
        maxloc1 <- str_locate(as.character(df$value[i]), as.character(max1))[1,1]
        if (maxloc1 == len_num){
                new_num <- str_replace(df$value[i], as.character(max1), "0")
                max1 <- max(as.numeric(str_extract_all(new_num, "") |> unlist()))
                maxloc1 <- str_locate(as.character(new_num), as.character(max1))[1,1]
        }
        new_series <- str_sub(df$value[i], maxloc1 + 1, len_num)
        max2 <- max(as.numeric(str_extract_all(new_series, "") |> unlist()))
        print(as.numeric(paste0(max1, max2)))
        sum_num <- sum_num + as.numeric(paste0(max1, max2))
}

sum_num
```

### PUZZLE


```{r}
puzzle1 <- read_lines(here("day3_puzzle1.txt")) |>
        as_tibble() 

df <- puzzle1

sum_num <- 0

for (i in 1:nrow(df)){
        len_num <- str_length(as.character(df$value[i]))
        max1 <- max(as.numeric(str_extract_all(df$value[i], "") |> unlist()))
        maxloc1 <- str_locate(as.character(df$value[i]), as.character(max1))[1,1]
        if (maxloc1 == len_num){
                new_num <- str_replace(df$value[i], as.character(max1), "0")
                max1 <- max(as.numeric(str_extract_all(new_num, "") |> unlist()))
                maxloc1 <- str_locate(as.character(new_num), as.character(max1))[1,1]
        }
        new_series <- str_sub(df$value[i], maxloc1 + 1, len_num)
        max2 <- max(as.numeric(str_extract_all(new_series, "") |> unlist()))
        print(as.numeric(paste0(max1, max2)))
        sum_num <- sum_num + as.numeric(paste0(max1, max2))
}

sum_num
```

## PUZZLE 2

### TEST

```{r}
df <- test1
sum_num <- 0
digit <- 12
num <- ""

for (i in 1:nrow(df)){
        len_num <- str_length(as.character(df$value[i]))
        series <- df$value[i]
        maxloc1 <- 1
        for (j in 1:12){
                max1 <- max(as.numeric(str_extract_all(str_sub(series, maxloc1, len_num-digit+j), "") |> unlist()))
                maxloc1 <- str_locate(as.character(series), as.character(max1))[1,1]
                new_series <- str_c(paste0(rep("0", maxloc1), collapse=""), str_sub(as.character(series), maxloc1+1, len_num))
                num <- paste0(num, as.character(max1))
                series <- new_series
        }
        print(num)
        sum_num <- sum_num + as.numeric(num)
        num <- ""
}

as.character(sum_num)
```

### PUZZLE

```{r}
df <- puzzle1
sum_num <- 0
digit <- 12
num <- ""

for (i in 1:nrow(df)){
        len_num <- str_length(as.character(df$value[i]))
        series <- df$value[i]
        maxloc1 <- 1
        for (j in 1:12){
                max1 <- max(as.numeric(str_extract_all(str_sub(series, maxloc1, len_num-digit+j), "") |> unlist()))
                maxloc1 <- str_locate(as.character(series), as.character(max1))[1,1]
                new_series <- str_c(paste0(rep("0", maxloc1), collapse=""), str_sub(as.character(series), maxloc1+1, len_num))
                num <- paste0(num, as.character(max1))
                series <- new_series
        }
        print(num)
        sum_num <- sum_num + as.numeric(num)
        num <- ""
}

as.character(sum_num)
```

# DAY 4

## PUZZLE 1

### TEST & PUZZLE


```{r}
test <- read_lines(here("day4_test.txt")) |>
        as_tibble()  |>
        mutate(value = str_replace_all(value, "@", "1")) |>
        mutate(value = str_replace_all(value, "\\.", "0"))

puzzle <- read_lines(here("day4_puzzle.txt")) |>
        as_tibble()  |>
        mutate(value = str_replace_all(value, "@", "1")) |>
        mutate(value = str_replace_all(value, "\\.", "0"))

df <- puzzle
str_len <- str_length(df$value[1])    

df <- df  |>
        rowwise() |>
        mutate(value = str_extract_all(value, "") |> unlist() |> paste0(collapse="-")) |>
        separate_wider_delim(value, "-", names = paste0("value", 1:str_len)) |>
        mutate(across(where(is.character), ~as.numeric(.x)))

n_roll <- 0

for (i in 1:nrow(df)){
        for (j in 1:ncol(df)){
                if (i == 1 & j == 1 | i == nrow(df) & j == 1 | i == 1 & j == ncol(df) | i == nrow(df) & j == ncol(df)){ # corners
                        n_roll <- n_roll + df[i,j]
                } else if (i == 1){
                        if(sum(df[i,j-1], df[i+1,j-1], df[i+1,j], df[i,j+1], df[i+1,j+1]) < 4){ # 1st row
                        n_roll <- n_roll + df[i,j]
                        }
                } else if (j == 1){
                        if(sum(df[i-1,j], df[i-1,j+1], df[i,j+1], df[i+1,j+1], df[i+1,j]) < 4) { # 1st column
                        n_roll <- n_roll + df[i,j]
                        }
                } else if (i == nrow(df)){
                        if(sum(df[i,j-1], df[i-1,j-1], df[i-1,j], df[i-1,j+1], df[i,j+1]) < 4) { # last row
                        n_roll <- n_roll + df[i,j]
                        }
                } else if (j == ncol(df)){
                        if(sum(df[i-1,j], df[i-1,j-1], df[i,j-1], df[i+1,j-1], df[i+1,j]) < 4) { # last column
                        n_roll <- n_roll + df[i,j]
                        }
                } else if (sum(df[i-1,j-1], df[i-1,j], df[i-1,j+1], df[i,j-1], df[i,j+1], df[i+1,j-1], df[i+1,j], df[i+1,j+1]) < 4){
                        n_roll <- n_roll + df[i,j]
                }
        }
}
n_roll
```

## PUZZLE 2

### TEST & PUZZLE

```{r}
df <- test
str_len <- str_length(df$value[1])    

df <- df  |>
        rowwise() |>
        mutate(value = str_extract_all(value, "") |> unlist() |> paste0(collapse="-")) |>
        separate_wider_delim(value, "-", names = paste0("value", 1:str_len)) |>
        mutate(across(where(is.character), ~as.numeric(.x)))

n_roll <- 0.1
n_roll_pre <- 0.2
df_new <- df

while(n_roll != n_roll_pre & n_roll != 0){
        n_roll_pre <- n_roll
        for (i in 1:nrow(df)){
        for (j in 1:ncol(df)){
                if (i == 1 & j == 1 | i == nrow(df) & j == 1 | i == 1 & j == ncol(df) | i == nrow(df) & j == ncol(df)){ # corners
                        n_roll <- n_roll + df[i,j]
                        df_new[i,j] <- 0
                } else if (i == 1){
                        if(sum(df[i,j-1], df[i+1,j-1], df[i+1,j], df[i,j+1], df[i+1,j+1]) < 4){ # 1st row
                        n_roll <- n_roll + df[i,j]
                        df_new[i,j] <- 0
                        }
                } else if (j == 1){
                        if(sum(df[i-1,j], df[i-1,j+1], df[i,j+1], df[i+1,j+1], df[i+1,j]) < 4) { # 1st column
                        n_roll <- n_roll + df[i,j]
                        df_new[i,j] <- 0
                        }
                } else if (i == nrow(df)){
                        if(sum(df[i,j-1], df[i-1,j-1], df[i-1,j], df[i-1,j+1], df[i,j+1]) < 4) { # last row
                        n_roll <- n_roll + df[i,j]
                        df_new[i,j] <- 0
                        }
                } else if (j == ncol(df)){
                        if(sum(df[i-1,j], df[i-1,j-1], df[i,j-1], df[i+1,j-1], df[i+1,j]) < 4) { # last column
                        n_roll <- n_roll + df[i,j]
                        df_new[i,j] <- 0
                        }
                } else if (sum(df[i-1,j-1], df[i-1,j], df[i-1,j+1], df[i,j-1], df[i,j+1], df[i+1,j-1], df[i+1,j], df[i+1,j+1]) < 4){
                        n_roll <- n_roll + df[i,j]
                        df_new[i,j] <- 0
                }
        }
        }
        df <- df_new
        print(n_roll)
}

n_roll
```